version: '3'
services:
  usnpi_db:
    volumes:
      - "./npidata:/data"
      - "./build:/import"
    # image: aidbox/aidboxdb:0.0.1-alpha3
    image: postgres:10
    container_name: usnpi
    ports:
      - "5678:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: usnpi
      POSTGRES_PASSWORD: verysecret
  usnpi_es:
    volumes:
      - ./npidata/es:/usr/share/elasticsearch/data
      - "./build:/import"
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    container_name: usnpi-elastic
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
