version: '3'
services:
  usnpi_db:
    volumes:
      - "./npidata:/data"
      - "./build:/import"
    # image: aidbox/aidboxdb:0.0.1-alpha3
    image: postgres:10
    container_name: usnpi
    ports:
      - "5678:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: usnpi
      POSTGRES_PASSWORD: verysecret
